### ISSUE TITLE
Consider linking to example issues involving circular dependencies?

### ISSUE THREAD

**Issue by jcbhmr** [Gerrit0/circular-dependency-check#1]
Hello! 👋

I was wondering "gee... aren't ES modules tolerant of circular dedpendencies?"
Of course, some Googling leads to examples of bad times... 😆
https://github.com/metaplex-foundation/solita/issues/22
https://stackoverflow.com/questions/46589957/es6-modules-and-circular-dependency
https://github.com/nrwl/nx/issues/10290
https://github.com/nrwl/nx/issues/8313
https://github.com/vitejs/vite/issues/7893

Seeing an example scenario of when this action is useful is very nice! I notice from a Google search that https://github.com/TypeStrong/typedoc/issues/1173 pops up. It might be a good idea to put that issue in the readme? Maybe? 🤔

**Comment by Gerrit0** [comment]
PR welcome! It's definitely possible to have benign circular dependencies, but I found it easier to just ban them all in my projects than to work through issues with them later
